### ISSUE TITLE
General purpose DNS parsing library

### ISSUE THREAD

**Issue by vorner** [bluejekyll/trust-dns#1355]
Hello

I'm in a need for a library that is able to parse packets as seen on network for some analytical reasons (not acting as a server or client, just looking at the packets already there). From what I browse through the docs, the `trust-dns-proto` would probably be just what I need.

However, the documentation specifically says it is not really meant to be used by others and that there might be breaking changes, etc.

So what I would like to know is, how large the breakage might get between versions, or if there's some long-term vision to, besides having a client and server implementations, to also provide some kind of „General purpose parsing/manipulation library“ thing, or if you would rather point me to some different library for these purposes.

**Comment by bluejekyll** [comment]
Thanks for the question.

1) `trust-dns-proto` is absolutely the crate you want to use for what you've described.

2) On the documentation, we've had that verbiage in place since when we originally split everything into multiple crates a few years ago. At that point, we were concerned about potentially restricting the project to forward compatibility in the proto layer, and slow down development. So we wanted to give guidance that folks who depend on it directly might experience more breaking changes than would occur with the other higher-level crates. In practice I don't think there is any significant difference in that experience.

**Comment by vorner** [comment]
Thank you! :-)

So should this track the update of README, or be closed?

**Comment by bluejekyll** [comment]
We can leave this open until (you?) someone has some time to remove that text from the README.
