### ISSUE TITLE
CachingClient::cache uses an immutable &self

### ISSUE THREAD

**Issue by Noah-Wagner** [bluejekyll/trust-dns#1615]
I found the following function where we insert new cache entries: [caching_client.rs]( https://github.com/bluejekyll/trust-dns/blob/main/crates/resolver/src/caching_client.rs#L465). 

I am new to Rust and don't understand all of the idioms, but it is a little surprising to me that the `&self` for this function is immutable, as we appear to modify the `CachingClient::lru_cache`. While this compiles (due to Arc/Mutex mutability), I wonder if it would make sense to also make the `&self` here mutable to clearly document that we are mutating state on our class?

**Comment by djc** [comment]
It's a desirable property for the `Resolver` or `AsyncResolver` to have resolving methods take `&self` rather than `&mut self` so you can share a single resolver in an `Arc` and easily run queries from different threads or tasks. Conceptually it also makes sense that a `Resolver` is not mutated whenever you run a resolver query. However, caching somewhat breaks that concept -- therefore the cache, in this case in the form of the `CachingClient`, contains an inner `Arc<Mutex<_>>` to make sure that the outward appearance of immutability isn't "broken".

Does that make sense?

**Comment by Noah-Wagner** [comment]
This makes sense, thanks!
