### ISSUE TITLE
Who uses Trust-DNS authoritative server in production? 

### ISSUE THREAD

**Issue by azzamsa** [bluejekyll/trust-dns#1694]
Hi.

IMHO, it is better to have a list of individual or company that uses Trust-DNS authoritative server  in the production environment.

**Comment by djc** [comment]
Why do you want to know, and what do you want to know exactly? This is a fairly vague question. Trust-DNS is a big project, so different parts of the project might have different levels of maturity/popularity.

**Comment by azzamsa** [comment]
Hi, I think I am missing the "authoritative server" word.

For the context. We have been using Knot DNS authoritative server for over 2 years in production. But every one or two week we always got the same memory issue. We have reported the issue upstream. They responded and helped us well. But the issue persist even on the latest revision.

We would like to try Trust DNS authoritative server. And see if it meets all our requirements. ( I think it will be). But we will try it first. Currently, our [digs](https://github.com/BiznetGIO/digs) app. Already depends on one of trust DNS component for over a year.

I have asked about this idea [here](https://discord.com/channels/590067103822774272/590067103822774274/957209620756201512), and Benjamin gives a green signal.

**Comment by Darkspirit** [comment]
If I can trust my calendar, I finally removed PowerDNS on 2019-03-02 and use Trust-DNS as my only authoritative dns server since then (zones with DNSSEC P-384 via ring, CAA validationmethods=dns-01).
I use an own incomplete/dirty written Rust app for ACME via DNS (Dynamic update via Trust-DNS client #556, Reqwest, Rustls) that also sets TLSA records for Web, Postfix, Prosody and reloads them.

I just noticed that I last updated my Trust-DNS server on 2021-03-02 as I haven't encountered any bugs since then, so I'm likely still on 0.20.0: https://github.com/bluejekyll/trust-dns/blob/main/CHANGELOG.md#0200
I'll update it later.

If I remember correctly, Trust-DNS is also used by Fuchsia, Google's Android successor.

**Comment by jeff-hiner** [comment]
Right now my team is prototyping an implementation of trust-dns-server tied to trust-dns-resolver as a proxy. I don't believe we're using it in production for authoritative name servers.

**Comment by peterthejohnston** [comment]
> @peterthejohnston are you willing/able to go on the record about how you use trust-dns?

Sure, happy to. We use Trust-DNS's [resolver](https://crates.io/crates/trust-dns-resolver) crate (with some Fuchsia-specific wrapper/integration code) as the production system DNS resolver for Fuchsia (see [here](https://cs.opensource.google/fuchsia/fuchsia/+/main:src/connectivity/network/dns/) for the code). Last year Fuchsia was launched on the first-gen Nest Hub, so it's been used in production since then.

We don't use the Trust-DNS server crate, though, which I guess was the original question here.

**Comment by dns2utf8** [comment]
I use it as a network debugging tool for myself and my clients: [dynamic.estada.ch](https://dynamic.estada.ch/)
It is publicly accessible. However, there is no SLA yet, as noone is paying me yet ;)

**Comment by azzamsa** [comment]
Thanks everyone!
Now I have clear view about the usage of Trust-DNS components in the wild.

**Comment by azzamsa** [comment]
Closing as this issue is not actionable. Should be in "discussion" section.
