### ISSUE TITLE
WARNs emitted on TCP disconnects

### ISSUE THREAD

**Issue by olix0r** [bluejekyll/trust-dns#1880]
We had users report WARNs being emitted in application logs. When looking more closely at debug logs we see something like:

```
[ 656.276898s] DEBUG ThreadId(01) trust_dns_proto::tcp::tcp_stream: zero bytes read, stream closed?
[ 656.276905s] WARN ThreadId(01) trust_dns_proto::xfer::dns_multiplexer: stream TCP(10.100.0.10:53) error: stream closed
```

It seems inappropriate to surface WARNs on such an innocuous internal event to me. As a workaround, we're going to add `trust_dns=ERROR` to our default log filter to exclude these types of things.

Would PRs be accepted to reduce log level for these types of innocuous events?

**Comment by djc** [comment]
In principle, yes!

**Comment by bluejekyll** [comment]
Yeah, I think it's safe to make all of these DEBUG statements, or were you thinking TRACE?

**Comment by olix0r** [comment]
`DEBUG` seems appropriate to me, too. I think @hawkw is going to take a look at fixing this.

**Comment by hawkw** [comment]
It looks like the error is already logged at `DEBUG` if there are no pending requests, and it's only logged at `WARN` if there are: https://github.com/bluejekyll/trust-dns/blob/3235d2b3f6433271f71780963936edab541c2ff3/crates/proto/src/xfer/dns_multiplexer.rs#L201-L205

It looks like this error is being logged because it's handled by returning `None` from the `Stream` impl, rather than by returning an error, so the error itself isn't actually propagated to user code: https://github.com/bluejekyll/trust-dns/blob/3235d2b3f6433271f71780963936edab541c2ff3/crates/proto/src/xfer/dns_multiplexer.rs#L417

Changing this code to just always log at `DEBUG` seems reasonable to me. However, if there is a desire to log some errors at `WARN`, perhaps we ought to make that decision based on the error kind as well as whether there are pending requests? That way, there's not a warning for TCP streams closing, but there could still be a warning for protocol errors that are less likely to occur...
