### ISSUE TITLE
Consider the CN (DNS Name, SPKI) of the TLS request

### ISSUE THREAD

**Issue by bluejekyll** [bluejekyll/trust-dns#216]
See https://news.ycombinator.com/item?id=15354120

It's possible that it would be better to have the certs be signed with IP addresses in the alternative subject fields, rather than name, as the name is somewhat irrelevant. It's the IP that's being used to for connection establishment.

**Comment by TerraX-net** [comment]
Chrome deprecated CN and only pays attention to SAN (DNS/IP). That should be done everywhere.
If I'm not wrong, Letsencrypt does not issue certificates for ip addresses.
Using a CA for DNS over TLS is another killswitch/point of failure and is not an ideal solution in my opinion.
The com zone may contain "example.com NS ns1.example.com" + "ns1.example.com A <ip4>". So trustdns should have a cert for ns1.example.com. For the case that one trustdns instance is known under different nameserver domains, it should support SNI to select the correct certificate. Otherwise one has to make sure that all possible names are SAN entries in the one and only certificate.

[DNSSEC/DANE chain stapling](https://datatracker.ietf.org/doc/draft-ietf-tls-dnssec-chain-extension/) (similar to OCSP stapling) will be used for [_443._tcp. TLSA](https://bugzilla.mozilla.org/show_bug.cgi?id=672600#c65)
and [_53._tcp. TLSA](https://tools.ietf.org/html/draft-ietf-dprive-dtls-and-tls-profiles-11#section-8.2.2) for example.

**Comment by bluejekyll** [comment]
If I understand your comment, then this is the current configuration on the client. It is expected that you would validate the cert with `ns1.example.com`. On the server side, I currently don't have SNI implemented. But it should be feasible to change the current server wide cert for certs per zone and use SNI to select the current cert.

**Comment by briansmith** [comment]
> If I understand your comment, then this is the current configuration on the client. It is expected that you would validate the cert with ns1.example.com.

AFAICT, Trust-DNS client will do the correct thing when using Rustls, automatically. This is because Rustls was designed to do the correct thing by default.

> On the server side, I currently don't have SNI implemented. But it should be feasible to change the current server wide cert for certs per zone and use SNI to select the current cert.

Rustls makes this pretty easy to do, as it has a callback interface for looking up the cert by SNI name already.
