### ISSUE TITLE
failure to parse a valid zone file

### ISSUE THREAD

**Issue by little-dude** [bluejekyll/trust-dns#314]
I'm taking a look at deckard as suggested in https://github.com/bluejekyll/trust-dns/issues/219, and the server tests are failing because trust-dns fails to parse this zone file:

```
$ORIGIN example.com.
$TTL 3600

@	SOA	dns1.example.com. hostmaster.example.com. (
		2010111213	; serial
		6h		; refresh
		1h		; retry
		1w		; expire
		1d )		; minimum

	NS	dns1
	NS	dns2
	MX	10 mail

dns1	A	192.0.2.1
	AAAA	2001:DB8::1

dns2	A	192.0.2.2
	AAAA	2001:DB8::2

mail	A	192.0.2.3
	AAAA	2001:DB8::3
```
There are two issues:

- the parser does not support the specifiying times with letters such as `6h`, `2w` or `1d`.
- the parser does not support implicit record class, you have to explicitely set it to `IN`

**Comment by bluejekyll** [comment]
> the parser does not support the specifiying times with letters such as 6h, 2w or 1d

This one surprises me, because I know I added support for it, we should add a test case for that specifically:

https://github.com/bluejekyll/trust-dns/blob/master/client/src/serialize/txt/master.rs#L385-L423

> the parser does not support implicit record class, you have to explicitely set it to IN

We can default to IN, I don't have a problem with that. It's been a while since I looked at this code, but I think the default is set to the last Record seen, so it should be as simple as setting this to `Some(DNSClass::IN)` instead of `None`:

https://github.com/bluejekyll/trust-dns/blob/master/client/src/serialize/txt/master.rs#L150

**Comment by davepacheco** [comment]
In case it's helpful to anyone else, the error message I saw was:

```
Error { kind: ParseInt(ParseIntError { kind: InvalidDigit }) }', bin/src/named.rs:405:27
```

This issue helped me find the problem (using times like "1h" in the SOA record) and work around it.  Thanks!

**Comment by davepacheco** [comment]
I cloned the default branch and built it yesterday.  I was on commit 8515a4321f796aaccc84ed1c3954e3f302941d9f.

**Comment by bluejekyll** [comment]
And was the lack of `IN` on the records the issue that triggered this for you?

**Comment by bluejekyll** [comment]
i.e. if we use the above config as a reference, would that cover your use case as well?

**Comment by davepacheco** [comment]
It appeared to be the use of human-readable times (like "1h") that did it.  When I changed all of those to an integer number of seconds, it worked.  When I changed any of them back, I got that error.

**Comment by davepacheco** [comment]
Yup, it was in the SOA record.
