### ISSUE TITLE
Support *ring* in addition to OpenSSL

### ISSUE THREAD

**Issue by bluejekyll** [bluejekyll/trust-dns#41]
Depends on 

https://github.com/briansmith/ring/pull/226

**Comment by djc** [comment]
*ring*-0.4.1 was just released, which has the primitive RSA verification API that you needed.

**Comment by bluejekyll** [comment]
thanks for the update!

I'll start looking into porting to this.

**Comment by djc** [comment]
Cool. I'm now subscribed to this, so if you run into any problems (that you're not sure are *ring* bugs) feel free to post them here.

**Comment by bluejekyll** [comment]
Cool, I'm working on some other things with futures, etc. right now. So it might be a week or two before I get started on this.

**Comment by briansmith** [comment]
I think it might be easier to do #43 before this. Then the client and server sides could be done separately. As far as *ring*'s functionality is concerned, I think it implements all the client-side stuff, but it hasn't yet implemented RSA keygen or ECDSA signing for server-side stuff. ECDSA signing is relatively easy to add to *ring* but it might be a while before RSA keygen comes up. I imagine, though, that there's a lot more interest in getting *ring* + the TrustDNS client working than *ring* + the TrustDNS server, because the weight of OpenSSL matters much less for servers than clients (IMO).

**Comment by bluejekyll** [comment]
That's a great idea.

I looked briefly at splitting the Client/Server just the other day. I'm planning to work on that after I complete my futures work.

**Comment by briansmith** [comment]
The client/server split seems to have been done in #68.

Regarding RSA support in *ring*, keep in mind that *ring* currently only supports RSA public keys of 2048 bits and larger. IIUC, the current root key is 1024 bits and "The new key signing key will be available on the Internet Assigned Numbers Authority website in February 2017, and it will appear in the DNS for the first time on July 11, 2017." See also https://blog.verisign.com/security/increasing-the-strength-of-the-zone-signing-key-for-the-root-zone-part-ii/. I don't know the schedule for the entire DNSSEC hierarchy to move to 2048-bit keys, though.

Regarding ECDSA verification in *ring* using the fixed-length eky format, it should be done within November.

I filed #60 to add EdDSA support to Trust-DNS. Note that EdDSA support in *ring* is already done, both for signing and verification. It might make sense to try EdDSA first.

**Comment by bluejekyll** [comment]
This is the current root key used in Trust-DNS: https://github.com/bluejekyll/trust-dns/blob/master/client/src/rr/dnssec/Kjqmt7v.pem

It's 2048, so that should be good, no?

**Comment by briansmith** [comment]
> This is the current root key used in Trust-DNS: https://github.com/bluejekyll/trust-dns/blob/master/client/src/rr/dnssec/Kjqmt7v.pem
> 
> It's 2048, so that should be good, no?

*ring* supports keys from 2048 through 8192 bits, so that's good. Whether all or enough of the RSA keys underneath the root key are 2048+ bits is another issue. That is, either you might decide that Trust-DNS is only going to support secure key sizes, in which you are good to go with *ring* for RSA, and/or you might want to find out how frequently smaller keys are still being used.

**Comment by bluejekyll** [comment]
ah yes... I think we can wait until someone decides they want that. for now, assuming that we'll only validate secure key sizes is fine for my own use cases.

**Comment by bluejekyll** [comment]
FYI, ed25519 support just landed in master. My plan right now is to support both openssl and ring in through features.

**Comment by bluejekyll** [comment]
Landed in master. Ring is an optional feature, as I had some compile issues in 1.13, current min version for trust-dns.

--features=ring
