### ISSUE TITLE
Evaluate if ResolverFuture can be Sync

### ISSUE THREAD

**Issue by bluejekyll** [bluejekyll/trust-dns#429]
It's thread safe, it should be Sync. It appears that ResolveError may be making ReslverFuture !Sync.

It's possible this will be helpful: https://github.com/rust-lang-nursery/error-chain/pull/241

**Comment by hawkw** [comment]
There's been [an assertion that `ResolverFuture` is `Sync`](https://github.com/bluejekyll/trust-dns/blob/0105b8188a6a2f1f9f03b05772c1eb7c09e68965/resolver/src/resolver_future.rs#L389) in the `ResolverFuture` tests since 0bf7909b76ab2b07a459ece61563a06e9942f3fd, I'm assuming this issue has been resolved?
