### ISSUE TITLE
Split ResolverFuture::new() into two returns (ResolverHandle, ResolverRuntime)

### ISSUE THREAD

**Issue by bluejekyll** [bluejekyll/trust-dns#464]
Names TBD.

At the moment, `ResolverFuture` returns a lazily evaluated future of `Self`. This makes it complicated to use in multithreaded situations. The reason for this is that there are really two separate parts to the resolver, but one is hidden at the moment. The hidden part is the registration of the network connections, etc, in the `NameServerPool` and it's associated `NameServer`s.

The proposed `ResolverHandle` (name TBD) would have an API identical to `ResolverFuture` today. It's responsibility would be identical to that of the `ResolverFuture` today, which is to use the handles to the `NameServers` to make requests.

The `ResolverRuntime` needs to be run in the background. This can be on the same thread as the `ResolverHandle` requests or on a separate thread. It should be spawned, and shut itself down when there are no more `ResolverHandle's` outstanding to it. To refactor the library to return this future, rather than spawning implicitly will take a bit of work, potentially all the way down into the proto library.

This should improve the experience of constructing and then using the Resolver...

**Comment by hawkw** [comment]
I have some thoughts on how to do this. I'd be happy to start a branch.

**Comment by bluejekyll** [comment]
I’m open to other proposals as well... this was just my first take on what might be needed.

**Comment by hawkw** [comment]
Well, I'm not going to make any promises until it's done, but I _think_ I've worked out a way of making this change without touching anything outside of the resolver crate. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hawkw** [comment]
Okay, I have a working first pass on this in [this branch](https://github.com/bluejekyll/trust-dns/compare/master...hawkw:eliza/split-resolver-future?expand=1). 

In particular, you may want to check out [this test I added](https://github.com/hawkw/trust-dns/blob/5ad62f466e037245da35c8ed6c25c2c76704e83e/resolver/src/resolver_future.rs#L605-L639), demonstrating that we can run the background task in a separate runtime on its' own thread from the futures returned by the `ResolverHandle`.

This branch probably still needs a little more polish before its' ready for prime-time. I think some of the code can be cleaned up, and it probably needs more documentation updates. Also, I suspect we can use this change to make the blocking `Resolver` implementation a bit smarter, by reusing the event loop and background task across resolutions, but that might end up getting its' own PR...

<details>

<summary> some notes</summary>

I named the background task `Background` rather than `ResolverRuntime`, as that name seems to imply that it _owns_ a runtime rather than that it _should be spawned on a runtime_; however, I'm happy to rename things. 

Also, note that a lot of the complexity in this branch is due to that I didn't want to make the whole resolver API return `Box<Future<...>` or `impl Future<...>`, everywhere, so there's a few kind of ugly type aliases; however, I think they're worth it because we can still return concrete types.
</details>
