### ISSUE TITLE
Upgrade OpenSSL to 0.8.x

### ISSUE THREAD

**Issue by zsck** [bluejekyll/trust-dns#50]
Before the upgrade to *ring*, I'd like to request that trust-dns adopt rust-openssl version 0.8.  I found in my use of rust-openssl in rust-ftp that some usage of rust-openssl version 0.7 lead to a memory error that was resolved immediately by the update to 0.8.

For a tiny bit more information, see the [issue I opened on hyperium/hyper](https://github.com/hyperium/hyper/issues/907).

**Comment by bluejekyll** [comment]
If you want to submit a PR for that, I'd happily accept.

**Comment by bluejekyll** [comment]
I started work on this to hopefully fix Travis OSX builds, but man, openssl 0.8.0 is quite different from 0.7 :(

**Comment by zsck** [comment]
It is pretty different. I'd have liked to get to this myself but have been over-loaded with other things.

**Comment by bluejekyll** [comment]
2b14581 is the conversion to openssl 0.8.

While that's basically complete, of corse my integration tests for the proof of a signed example.com are now failing :(

looking into it.

**Comment by bluejekyll** [comment]
oh, and I have all the warnings related to the futures stuff cleaned up in a different branch. I'll be getting rid of those in a little bit.

**Comment by bluejekyll** [comment]
Travis is passing again with this patch at least :)

**Comment by bluejekyll** [comment]
FYI, looking more deeply, not all secure queries are failing, and some parts of the chain are validating properly. I'm not entirely able to say right now that there isn't a bug here. rollernet tests are all passing right now, which tells me that it's only example.com that is having issues.

It validates the www.example.com against example.com's DNSKEY, but then fails to validate the DNSKEY for example.com. But since rollertnet tests are functioning this might not be an issue with the upgrade.

**Comment by bluejekyll** [comment]
`cargo test -- --ignored` will run all of the integration tests for anyone interested in looking at this.

**Comment by bluejekyll** [comment]
Ok, got to the bottom of it. In changing a bunch of interfaces to return Result (due to some of the changes in OpenSSL), I had made overzealous use of try!() and underthought placement in the validation loops for DNSSec. Everything checks out now.
