### ISSUE TITLE
Server should support wildcards

### ISSUE THREAD

**Issue by rushmorem** [bluejekyll/trust-dns#510]

**Comment by bluejekyll** [comment]
I think this should look similar to this lookup path: https://github.com/bluejekyll/trust-dns/blob/master/server/src/authority/authority.rs#L1022-L1039

Which may need a separate variant for the Iterator: https://github.com/bluejekyll/trust-dns/blob/master/server/src/authority/authority.rs#L1381

**Comment by rushmorem** [comment]
I think the fix for this is even simpler than that. The problem is we are calling `get(&rr_key)` which does exact matches. We simply need to replace that with `Authority::find` which does something similar to what `Catalog::find` does. If a `get` fails to find any results, we need to replace the first label with `*` and see if we can find any results, taking provisions of RFC 1034 into account.

**Comment by bluejekyll** [comment]
I haven't read that part of the RFC in a while. I pointed to that custom iterator, mostly because that Iterator is efficient for a full scan of the records in the zone, which `*.example.com` might need. But if you think it would be efficient and easy to do this differently, then I'm definitely open to that.

**Comment by bluejekyll** [comment]
Fixed in https://github.com/bluejekyll/trust-dns/commit/a43aff634b7f7883c74cffb3a5c776583df84217
