### ISSUE TITLE
packet injection vulnerability

### ISSUE THREAD

**Issue by aep** [bluejekyll/trust-dns#629]
It looks like the udp resolver accepts responses from any address, 
not just the server it sent a request to. I'm not sure if this is a problem,  since you'd have to guess the local port. 

Maybe in high load environments with lots of outgoing pending dns requests, this could be abused. Like  when implementing a dns server with upstream queries and someone can guess the port for the upstream response.

[edit]

Actually i'm reasonably sure now this is a real problem. There's a bunch of script kiddies doing exactly that on public wifi. You can easily see the source port on the air and just reply faster than an internet server.

**Comment by aep** [comment]
hah, thanks for the instant response.
That sounds bad. I'll dig around what everyone else does.

**Comment by bluejekyll** [comment]
This is explicitly allowed in an RFC, and I can't remember which one. The tactic is to randomize port selection on outbound as well as the DNS request ID>

**Comment by bluejekyll** [comment]
Of course I can't find any history of having actually enabled that, which means I may have done that to match the original RFC, but this is clarified here: https://tools.ietf.org/html/rfc2181#section-4

Not sure why I didn't enforce that instead of logging. I think I was trying to discover if it would be an issue and never went back and enforced it. I don't see any issues, or history in the code that it was ever enforced. So we should just drop the response.

Do you want to submit a change?

**Comment by aep** [comment]
yup. fix looks easy

**Comment by kpcyrd** [comment]
I don't think it's common that a wrong IP in the response is filtered.

I ran into this in a real setup this summer (south western railway wifi if I recall correctly), in which my trust-dns based program had trouble getting dns to work, while everything else just worked. After some digging I noticed the response is coming from an IP I didn't ask (talking directly to THAT ip returned nothing though).

This meant lookups with dig and trust-dns failed, but everything glibc based was just working fine. I asked a few friends and apparently I was the only person having issues with that kind of setup.

**Comment by bluejekyll** [comment]
I'm confused, are you saying that trust-dns was failing b/c of the filtering (which I don't think is happening now) or for some other reason? Because over UDP, trust-dns I don't think is currently filtering out based on src address of the Nameserver. We might be filtering further up the stack, but I didn't find than in the `UdpClientStream`, I'll dig deeper tonight.

**Comment by kpcyrd** [comment]
I think I mixed up the trust-dns part, this was half a year ago and I didn't pay too much attention back then (since I was on a train). I think trust-dns couldn't resolve it since talking to the ip that was pushed over dhcp didn't work (so I don't know if trust-dns would've accepted or rejected the reply), but /etc/resolv.conf listed 8.8.8.8, which was hijacked by the network (along with everything else on port :53, but always replied from the same ip that was the dns server according to dhcp)

both dig and glibc based programs talked to 8.8.8.8, dig was logging an error because the src ip of the reply didn't match, but glibc happily accepted those replies. My point is that I don't think glibc is rejecting these by default.

**Comment by bluejekyll** [comment]
I’m not sure what the solution is here, as it’s an abuse that others are exploiting, and would cause a perception of failure.

> I think trust-dns couldn't resolve it since talking to the ip that was pushed over dhcp didn't work 

This DHCP generally overwrites the resolve.conf, but trust-dns currently doesn’t have a “reload” mechanism on change of that file. It could be it changed, and the update was never picked up.

**Comment by bluejekyll** [comment]
I should note, the src  addr in UDP is not trusted anyway, which means that even matching on this wouldn’t really make the packet trustworthy. Only DNSSEC and/or DoH/DoT provide protections against that.

**Comment by aep** [comment]
> My point is that I don't think glibc is rejecting these by default.

glibc is pretty difficult to read, so there might be a fallback somewhere i didnt find. However, android does reject it correctly, which is probably the most popular OS on the planet, so people will notice broken dns servers already.

**Comment by bluejekyll** [comment]
One option is thinking about is that we could “capture” the first response (ie the one that doesn’t match the remote src addr), and set a timer of say a second to see if the if the correct one shows up, if the timer goes off, return the only one we received, otherwise return the on that matches in the future.

**Comment by bluejekyll** [comment]
Any objections to the idea to fall back to the wrongly src’d packet in the case of a timeout?

I think that will strike a nice balance between function and improved authenticity of the src (though not strong, better). I can merge #630 and then make that change if there are no objections.

**Comment by aep** [comment]
@bluejekyll no real objection, although i do think the timeout has to be significant, like a second at least.
