### ISSUE TITLE
Lookup results should implement `IntoIterator`

### ISSUE THREAD

**Issue by Benjamin-L** [bluejekyll/trust-dns#730]
I'm trying to return a mapped iterator over `LookupIp` from a function. This doesn't work right now without first collecting the `LookupIpIter` into a container, and then calling `into_iter`. This is because `LookupIpIter` borrows `LookupIp`, so you can't return it from a function since it borrows a local variable.

Ideally, all of the `*Lookup*` structs that have an `iter` method should also implement `IntoIterator` so that you can do this type of thing. It would behave identically to the current iterators, except that it would own the lookup struct rather than borrowing it.

Obviously, the `.collect::<Vec<_>>().into_iter()` approach *does* work, but it's both extra boilerplate and less efficient.

**Comment by bluejekyll** [comment]
This is a good suggestion. I’m happy to take pull requests. Otherwise I’ll play around with this when I have some time.

**Comment by bluejekyll** [comment]
So looking at this, there's a bit of a complication, which is that ideally the interface would look like this: 

```rust
impl IntoIterator for Lookup {
    type Item = RData;
    type Iterator = LookupIntoIter;

    fn into_iter(self) -> LookupIntoIter {
        unimplemented!()
    }
}
```

The issue is that the Lookup types wrap an `Arc` of the `Vec` of the returned records. This is because the records are cached and returned from the cache. What we can do is `Arc::try_unwrap`, but this will generally fail, and we'll end up cloning the internal `Vec`, thus being a costly conversion. As an ease of use thing, this is fine, but it's too bad that it will incur this cost.

**Comment by bluejekyll** [comment]
Ok, see #734 for an my suggested implementation. Let me know if you had something else in mind.
